name: "Genshin Impact Daily Check-in Remainder"

on:
  schedule:
    - cron: "0 13 * * *"  # Minute/Hour/Day/Month/Weekday (UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v2.0.2
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          raw-data: content.json
