name: "Genshin Impact Daily Check-in Remainder"

on:
  schedule:
    - cron: "0 0,13 * * *"  # Minute/Hour/Day/Month/Weekday (UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v2.0.2
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          raw-data: content.json   

      # - name: Get Embbeded Message
      #   id: message
      #   run: echo ::set-output name=content::$(cat content.json)

      # - name: Test output
      #   run: echo ${{ steps.vars.outputs.content }}

      # - name: Sending Message
      #   uses: fjogeleit/http-request-action@master
      #   with:
      #     url: ${{ secrets.DISCORD_WEBHOOK }}
      #     method: 'POST'
      #     data: ${{ steps.vars.outputs.content }}